# Generated by Django 3.1 on 2021-07-09 18:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 46, 29, 569522, tzinfo=utc), verbose_name='first available')),
                ('mrp', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('storename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
