# Generated by Django 3.1 on 2021-07-10 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grokartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 3, 11, 54, 848469, tzinfo=utc), verbose_name='first available'),
        ),
    ]
