# Generated by Django 3.1 on 2021-07-10 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grokartapp', '0002_auto_20210710_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 9, 4, 40, 479962, tzinfo=utc), verbose_name='first available'),
        ),
    ]
