# Generated by Django 3.1 on 2021-07-10 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grokartapp', '0005_auto_20210710_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 16, 48, 18, 128225, tzinfo=utc), verbose_name='first available'),
        ),
    ]
