# Generated by Django 3.1 on 2021-07-11 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grokartapp', '0007_auto_20210710_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 2, 49, 41, 736794, tzinfo=utc), verbose_name='first available'),
        ),
    ]
