# Generated by Django 3.1 on 2021-07-11 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grokartapp', '0008_auto_20210711_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 2, 53, 32, 818175, tzinfo=utc), verbose_name='first available'),
        ),
    ]
